names = {'LPA','RPA','CPF','LPF','RPF'};

left_idx = [1 4];
right_idx = [2 5];
central_idx = 3;

ernie_markers = ...
  [4.1972      	86.718      	-41.673;...
    -0.51881     -86.502       	-55.85;...
    104.83       1.6435       	1.6432;...
    88.576       44.618      	-1.2635;...
    94.947       -41.09    		-3.0135];


ernie_points = ...
   [-34.768		-207.46         -59.945;...
    -22.456		-46.491       	-65.44;...
    32.22      	-140.07      	-159.15;...
    16.422      -182.98       	-147.1;...
    26.172      -100.34      	-155.37];

wl_markers = ...
    [2.786          81.899      	-30.817;...
    5.9745      	-76.725      	-41.904;...
    102.19       	3.0626       	12.452;...
    85.271       	49.342       	15.041;...
    94.024      	-39.732       	4.7156];

wl_points = ...
    [9.4471 		-182.6389   	-78.1391;...
    11.1093  		-30.9845  		-76.3349;...
    109.0490 		-112.7843 		-139.1564;...
    94.7899 		-154.2439       -130.9148;...
    96.9244  		-67.3969 		-133.7234];	


figure;
plot3(ernie_points(:,1),...
    ernie_points(:,2),...
    ernie_points(:,3),...
    'k.','MarkerSize',24);

text(ernie_points(:,1),...
    ernie_points(:,2),...
    ernie_points(:,3),...
    names)



figure;
plot3(wl_points(:,1),...
    wl_points(:,2),...
    wl_points(:,3),...
    'k.','MarkerSize',24);

text(wl_points(:,1),...
    wl_points(:,2),...
    wl_points(:,3),...
    names)


figure; 
plot3(ernie_markers(left_idx,1), ...
    ernie_markers(left_idx,2), ...
    ernie_markers(left_idx,3),...
    'k.','MarkerSize', 24)

hold on;
plot3(ernie_markers(right_idx,1), ...
    ernie_markers(right_idx,2), ...
    ernie_markers(right_idx,3),...
    'ks','MarkerSize', 12,...
    'MarkerFaceColor','k')

plot3(ernie_markers(central_idx,1), ...
    ernie_markers(central_idx,2), ...
    ernie_markers(central_idx,3),...
    'kd','MarkerSize', 12,...
    'MarkerFaceColor','k')


plot3(wl_markers(left_idx,1), ...
    wl_markers(left_idx,2), ...
    wl_markers(left_idx,3),...
    'r.','MarkerSize', 24)

plot3(wl_markers(right_idx,1), ...
    wl_markers(right_idx,2), ...
    wl_markers(right_idx,3),...
    'rs','MarkerSize', 12,...
    'MarkerFaceColor','r')

plot3(wl_markers(central_idx,1), ...
    wl_markers(central_idx,2), ...
    wl_markers(central_idx,3),...
    'rd','MarkerSize', 12,...
    'MarkerFaceColor','r')




figure; 
plot3(ernie_points(left_idx,1), ...
    ernie_points(left_idx,2), ...
    ernie_points(left_idx,3),...
    'k.','MarkerSize', 24)

hold on;
plot3(ernie_points(right_idx,1), ...
    ernie_points(right_idx,2), ...
    ernie_points(right_idx,3),...
    'ks','MarkerSize', 12,...
    'MarkerFaceColor','k')

plot3(ernie_points(central_idx,1), ...
    ernie_points(central_idx,2), ...
    ernie_points(central_idx,3),...
    'kd','MarkerSize', 12,...
    'MarkerFaceColor','k')


plot3(wl_points(left_idx,1), ...
    wl_points(left_idx,2), ...
    wl_points(left_idx,3),...
    'r.','MarkerSize', 24)

plot3(wl_points(right_idx,1), ...
    wl_points(right_idx,2), ...
    wl_points(right_idx,3),...
    'rs','MarkerSize', 12,...
    'MarkerFaceColor','r')

plot3(wl_points(central_idx,1), ...
    wl_points(central_idx,2), ...
    wl_points(central_idx,3),...
    'rd','MarkerSize', 12,...
    'MarkerFaceColor','r')


[Re, Te] = rot3dfit(ernie_points, ernie_markers);
TMe = [Re', Te'; 0 0 0 1];

[Rw, Tw] = rot3dfit(wl_points, wl_markers);
TMw = [Rw', Tw'; 0 0 0 1];


wl_points_to_markers = TMw(1:3,1:3) * wl_points';
e_points_to_markers = TMe(1:3,1:3) * ernie_points';

wl_points_to_markers_02 = bsxfun(@plus, wl_points_to_markers', TMw(1:3,4)');
e_points_to_markers_02 = bsxfun(@plus, e_points_to_markers', TMe(1:3,4)');

figure; 
plot3(e_points_to_markers_02(left_idx,1), ...
    e_points_to_markers_02(left_idx,2), ...
    e_points_to_markers_02(left_idx,3),...
    'k.','MarkerSize', 24)

hold on;
plot3(e_points_to_markers_02(right_idx,1), ...
    e_points_to_markers_02(right_idx,2), ...
    e_points_to_markers_02(right_idx,3),...
    'ks','MarkerSize', 12,...
    'MarkerFaceColor','k')

plot3(e_points_to_markers_02(central_idx,1), ...
    e_points_to_markers_02(central_idx,2), ...
    e_points_to_markers_02(central_idx,3),...
    'kd','MarkerSize', 12,...
    'MarkerFaceColor','k')


plot3(ernie_markers(left_idx,1), ...
    ernie_markers(left_idx,2), ...
    ernie_markers(left_idx,3),...
    'r.','MarkerSize', 24)

plot3(ernie_markers(right_idx,1), ...
    ernie_markers(right_idx,2), ...
    ernie_markers(right_idx,3),...
    'rs','MarkerSize', 12,...
    'MarkerFaceColor','r')

plot3(ernie_markers(central_idx,1), ...
    ernie_markers(central_idx,2), ...
    ernie_markers(central_idx,3),...
    'rd','MarkerSize', 12,...
    'MarkerFaceColor','r')




figure; 
plot3(wl_points_to_markers_02(left_idx,1), ...
    wl_points_to_markers_02(left_idx,2), ...
    wl_points_to_markers_02(left_idx,3),...
    'k.','MarkerSize', 24)

hold on;
plot3(wl_points_to_markers_02(right_idx,1), ...
    wl_points_to_markers_02(right_idx,2), ...
    wl_points_to_markers_02(right_idx,3),...
    'ks','MarkerSize', 12,...
    'MarkerFaceColor','k')

plot3(wl_points_to_markers_02(central_idx,1), ...
    wl_points_to_markers_02(central_idx,2), ...
    wl_points_to_markers_02(central_idx,3),...
    'kd','MarkerSize', 12,...
    'MarkerFaceColor','k')


plot3(wl_markers(left_idx,1), ...
    wl_markers(left_idx,2), ...
    wl_markers(left_idx,3),...
    'r.','MarkerSize', 24)

plot3(wl_markers(right_idx,1), ...
    wl_markers(right_idx,2), ...
    wl_markers(right_idx,3),...
    'rs','MarkerSize', 12,...
    'MarkerFaceColor','r')

plot3(wl_markers(central_idx,1), ...
    wl_markers(central_idx,2), ...
    wl_markers(central_idx,3),...
    'rd','MarkerSize', 12,...
    'MarkerFaceColor','r')









